# Generated by Django 5.1.6 on 2025-02-09 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_class_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Member',
        ),
    ]
